window.PREGNANCY_DATA = (() => {
  const reviewedAt = "2026-07-05";

  const sources = {
    pregnancyVoucher: "https://www.gov.kr/portal/service/serviceInfo/SD0000007672",
    easyLawMaternity:
      "https://www.easylaw.go.kr/CSP/CnpClsMain.laf?ccfNo=3&cciNo=5&cnpClsNo=1&csmSeq=735&popMenu=ov",
    pregnancyOneStop: "https://www.gov.kr/portal/onestopSvc/fertility",
    ktxBenefit: "https://www.gov.kr/portal/service/serviceInfo/B55145700016",
    postpartumHelper: "https://www.gov.kr/portal/service/serviceInfo/PTR000050390",
    fluShot: "https://nip.kdca.go.kr/irhp/infm/goVcntInfo.do?menuCd=134&menuLv=1",
  };

  const milestones = [
    {
      id: "voucher-apply",
      type: "pregnancy_week",
      week: 5,
      category: "benefit",
      title: "국민행복카드·진료비 지원 신청",
      shortTitle: "국민행복카드 신청",
      summary: "임신 확인 뒤 가능한 빠르게 건강보험 임신·출산 진료비 지원을 신청합니다.",
      details:
        "정부24 기준 임신 1회당 100만 원, 다태아는 140만 원 기본지급이며 다태아는 태아당 100만 원이 되도록 추가지원됩니다. 카드 발급과 지원 신청을 같이 처리하면 일정 관리가 쉽습니다.",
      why: "임신 확인 뒤 가장 먼저 챙길 공적 지원이라 초기에 배치했습니다.",
      sourceLabel: "정부24 건강보험 임신·출산 진료비 지원",
      href: sources.pregnancyVoucher,
      official: true,
    },
    {
      id: "one-stop-apply",
      type: "pregnancy_week",
      week: 5,
      category: "benefit",
      title: "맘편한 임신 원스톱 신청",
      shortTitle: "맘편한 임신 신청",
      summary: "정부24 맘편한 임신에서 임신 관련 지원을 한 번에 확인하고 신청합니다.",
      details:
        "엽산제, 철분제, 표준모자보건수첩, 맘편한 KTX, SRT 임산부 할인, 에너지바우처 등 연계 가능한 서비스를 한 화면에서 확인할 수 있습니다. 실제 제공 항목은 거주지와 자격에 따라 달라집니다.",
      why: "여러 혜택을 따로 찾기 전에 한 번에 묶어서 확인하는 출발점입니다.",
      sourceLabel: "정부24 맘편한 임신",
      href: sources.pregnancyOneStop,
      official: true,
    },
    {
      id: "work-short-early",
      type: "pregnancy_week",
      week: 5,
      category: "work",
      title: "임신기 근로시간 단축 가능 여부 확인",
      shortTitle: "근로시간 단축 검토",
      summary: "재직 중이라면 12주 이내 사용 가능한 임신기 근로시간 단축을 초기에 검토합니다.",
      details:
        "찾기쉬운 생활법령 기준 임신 후 12주 이내 또는 32주 이후 여성근로자는 1일 2시간 근로시간 단축을 신청할 수 있고, 사용자는 이를 이유로 임금을 삭감할 수 없습니다.",
      why: "초기 구간은 12주 이내로 짧아서 놓치기 쉬운 권리입니다.",
      sourceLabel: "찾기쉬운 생활법령정보",
      href: sources.easyLawMaternity,
      official: true,
      audience: "재직자",
    },
    {
      id: "folic-acid",
      type: "pregnancy_week",
      week: 5,
      category: "health",
      title: "엽산제 지원 신청 또는 수령",
      shortTitle: "엽산제 신청",
      summary: "임신초기부터 보건소 또는 맘편한 임신 경로로 엽산제 지원 여부를 확인합니다.",
      details:
        "정부24 맘편한 임신 안내 항목에 엽산제가 포함됩니다. 실제 수령 가능 시점과 수량은 보건소별 차이가 있을 수 있어 거주지 보건소 기준을 같이 확인하는 편이 안전합니다.",
      why: "임신초기부터 신청 가능한 대표 항목이라 가장 앞쪽에 배치했습니다.",
      sourceLabel: "정부24 맘편한 임신",
      href: sources.pregnancyOneStop,
      official: true,
    },
    {
      id: "maternal-handbook",
      type: "pregnancy_week",
      week: 5,
      category: "document",
      title: "표준모자보건수첩 발급 확인",
      shortTitle: "모자보건수첩 확인",
      summary: "임신초기부터 표준모자보건수첩 제공 여부를 확인합니다.",
      details:
        "정부24 맘편한 임신 안내 항목에 표준모자보건수첩이 포함됩니다. 실제 발급 방식은 온라인 신청 연계 또는 보건소 수령 등 지역별 차이가 있을 수 있습니다.",
      why: "초기 기록 관리와 안내 자료 역할을 하므로 빠르게 확인할 가치가 있습니다.",
      sourceLabel: "정부24 맘편한 임신",
      href: sources.pregnancyOneStop,
      official: true,
    },
    {
      id: "pregnancy-badge",
      type: "pregnancy_week",
      week: 5,
      category: "daily",
      title: "임산부 배지 제공 여부 보건소 확인",
      shortTitle: "임산부 배지 확인",
      summary: "임신 확인 직후 보건소나 병원에서 임산부 배지 제공 여부를 확인합니다.",
      details:
        "임산부 배지는 전국 공통 중앙서비스로 바로 확인되기보다 보건소·병원 제공 안내 형태가 많습니다. 따라서 신청 확정 일정이 아니라 초기 확인 항목으로 보는 편이 객관적입니다.",
      why: "대중교통과 외부 이동 시 바로 체감되는 편의 항목이라 초기 확인 가치가 있습니다.",
      sourceLabel: "보건소 또는 병원 개별 안내 확인",
      href: sources.pregnancyOneStop,
      official: false,
    },
    {
      id: "rail-register",
      type: "pregnancy_week",
      week: 8,
      category: "benefit",
      title: "맘편한 KTX·SRT 등록",
      shortTitle: "KTX·SRT 등록",
      summary: "철도 이용 계획이 있다면 임산부 할인 등록을 미리 끝냅니다.",
      details:
        "정부24 기준 KTX는 출산예정일 + 1년까지 특실·우등실 요금 면제 또는 일반실 운임 할인, SRT는 지정 좌석 운임 할인이 적용됩니다. 실제 조건은 예매 수량과 노선에 따라 다를 수 있습니다.",
      why: "임신 확인 뒤 증빙이 준비되면 바로 등록할 수 있는 혜택입니다.",
      sourceLabel: "정부24 맘편한 코레일",
      href: sources.ktxBenefit,
      official: true,
    },
    {
      id: "iron-supplement",
      type: "pregnancy_week",
      week: 16,
      category: "health",
      title: "철분제 지원 또는 수령 시기 확인",
      shortTitle: "철분제 확인",
      summary: "임신 중기 진입 시점에 철분제 지원 가능 여부를 다시 확인합니다.",
      details:
        "정부24 맘편한 임신 안내 항목에 철분제가 포함됩니다. 실제 제공 시작 주차와 수량은 보건소별 차이가 있어 중기 진입 시점에 다시 확인하는 방식이 실무적으로 맞습니다.",
      why: "철분제는 초기보다 중기 이후 체감도가 커서 별도 시점 포인트로 분리했습니다.",
      sourceLabel: "정부24 맘편한 임신",
      href: sources.pregnancyOneStop,
      official: true,
    },
    {
      id: "flu-shot",
      type: "pregnancy_week",
      week: 20,
      category: "health",
      title: "독감 국가예방접종 일정 확인",
      shortTitle: "독감접종 확인",
      summary: "임신부는 주수와 관계없이 인플루엔자 국가예방접종 대상이므로 절기 일정에 맞춰 확인합니다.",
      details:
        "질병관리청 안내 기준 임신부는 임신 주수와 관계없이 국가예방접종 지원 대상입니다. 다만 실제 접종 가능 기간은 절기별 공지 일정에 따르므로 해당 시즌 운영 기간을 함께 확인해야 합니다.",
      why: "주수 제한은 없지만 시즌성 일정이라 중기 시점에 미리 확인하도록 배치했습니다.",
      sourceLabel: "질병관리청 예방접종도우미",
      href: sources.fluShot,
      official: true,
    },
    {
      id: "work-short-late",
      type: "pregnancy_week",
      week: 32,
      category: "work",
      title: "32주 이후 근로시간 단축 재확인",
      shortTitle: "32주 단축 확인",
      summary: "32주 이후 다시 사용할 수 있는 임신기 근로시간 단축 여부를 확인합니다.",
      details:
        "초기 12주 구간을 넘겼더라도 32주 이후에는 다시 법정 신청 가능 구간이 열립니다. 회사 서식과 제출 시점을 미리 확인해 두는 편이 안전합니다.",
      why: "법상 가능 시점이 다시 열리는 기준 주차입니다.",
      sourceLabel: "찾기쉬운 생활법령정보",
      href: sources.easyLawMaternity,
      official: true,
      audience: "재직자",
    },
    {
      id: "postpartum-helper",
      type: "due_days_before",
      days: 40,
      category: "benefit",
      title: "산모·신생아 건강관리 지원 신청 준비",
      shortTitle: "산후도우미 신청",
      summary: "출산 전부터 산모·신생아 건강관리 지원 신청 일정을 잡습니다.",
      details:
        "정부24 기준 출산예정일 40일 전부터 출산일로부터 30일까지 신청할 수 있습니다. 복지로와 보건소 접수 방식, 소득기준, 필요서류가 지자체별로 다를 수 있어 사전 준비가 필요합니다.",
      why: "공식 신청 가능 시작점이 출산예정일 40일 전이기 때문입니다.",
      sourceLabel: "정부24 산모·신생아 건강관리 지원",
      href: sources.postpartumHelper,
      official: true,
    },
  ];

  return {
    reviewedAt,
    sources,
    milestones,
  };
})();
