window.PREGNANCY_DATA = (() => {
  const verifiedDate = "2026-07-04";
  const sources = {
    govPregnancy: "https://www.gov.kr/portal/onestopSvc/fertility",
    govMedicalVoucher: "https://www.gov.kr/portal/service/serviceInfo/SD0000007672",
    govKtx: "https://www.gov.kr/portal/service/serviceInfo/B55145700016",
    govPostpartumHelper: "https://www.gov.kr/portal/service/serviceInfo/PTR000050390",
    easyLawMaternity:
      "https://www.easylaw.go.kr/CSP/CnpClsMain.laf?ccfNo=3&cciNo=5&cnpClsNo=1&csmSeq=735&popMenu=ov",
    kdcaFlu: "https://nip.kdca.go.kr/irhp/infm/goVcntInfo.do?menuCd=134&menuLv=1",
  };

  const verificationLabels = {
    official: "공식 확인",
    partial: "일부 공식 확인",
    video: "영상 기반",
    needs_check: "개별 확인 필요",
    general: "일반 준비",
  };

  const tasks = [
    {
      id: "confirm-document",
      from: 4,
      to: 6,
      category: "hospital",
      verification: "video",
      title: "임신 확인서와 출산예정일 먼저 확정",
      body: "영상에서는 임신 확인서를 2-3장 받아두고 사진으로 저장하라고 안내합니다. 카드, 보건소, 직장, 보험사 제출에 반복 사용됩니다.",
      source: "영상: 임신 확인 후 첫 순서",
    },
    {
      id: "first-week-map",
      from: 4,
      to: 6,
      category: "personal",
      verification: "video",
      title: "첫 주 신청 순서 정리",
      body: "진료비 지원, 카드 발급, 보건소 등록, 영양제, 예약성 항목을 한 번에 처리하지 말고 필요한 증빙과 마감일 기준으로 나눕니다.",
      source: "영상: 첫 주 체크리스트",
    },
    {
      id: "happy-card",
      from: 4,
      to: 8,
      category: "official",
      verification: "official",
      title: "국민행복카드와 진료비 지원 먼저 처리",
      body: "정부24 기준 임신 1회당 100만 원, 다태아 140만 원 기본지급이며 다태아는 태아당 100만 원이 되도록 추가지원됩니다.",
      source: "정부24 건강보험 임신·출산 진료비 지원",
      href: sources.govMedicalVoucher,
      warning: "분만취약지는 20만 원 추가지원 여부 확인",
    },
    {
      id: "public-health",
      from: 4,
      to: 8,
      category: "official",
      local: true,
      verification: "official",
      title: "맘편한 임신으로 보건소 지원 묶어서 신청",
      body: "정부24 맘편한 임신에서 엽산제, 철분제, KTX/SRT 할인, 소득요건형 혜택, 지자체 임신축하 혜택을 한 번에 확인합니다.",
      source: "정부24 맘편한 임신",
      href: sources.govPregnancy,
    },
    {
      id: "pregnancy-badge",
      from: 4,
      to: 12,
      category: "official",
      local: true,
      verification: "video",
      title: "임산부 배지와 증빙 챙기기",
      body: "영상에서는 대중교통 이용 시 임산부 배지나 확인 서류를 지참하는 것을 추천합니다. 보건소 등록 때 받을 수 있는지 확인합니다.",
      source: "영상: 임신 직후 해야 할 일",
    },
    {
      id: "folic-acid",
      from: 4,
      to: 12,
      category: "hospital",
      local: true,
      verification: "video",
      title: "초기 영양제와 보건소 수령 시점 점검",
      body: "영상은 엽산을 임신 확인 당일부터, 비타민 D를 함께 시작하라고 안내합니다. 보건소 무료 수령 가능 여부도 먼저 확인합니다.",
      source: "영상: 초기 영양제 타이밍",
      warning: "복용량은 담당 의료진 기준 우선",
    },
    {
      id: "under-ten-weeks",
      from: 6,
      to: 10,
      category: "personal",
      verification: "video",
      title: "10주 전 끝낼 항목 분리",
      body: "영상에서 10주 전 항목으로 단축근무, 조리원, 산후도우미, 자동차보험 할인, 우체국 보험, 필수 앱, 출산병원 예약을 분리합니다.",
      source: "영상: 10주 전 준비",
    },
    {
      id: "short-work-hours",
      from: 4,
      to: 12,
      category: "official",
      verification: "official",
      title: "임신기 근로시간 단축 신청",
      body: "찾기쉬운 생활법령 기준 임신 후 12주 이내 또는 32주 이후 여성근로자는 1일 2시간 단축을 신청할 수 있고 임금 삭감은 금지됩니다.",
      source: "찾기쉬운 생활법령정보",
      href: sources.easyLawMaternity,
      warning: "개시 3일 전 문서와 진단서 제출 필요",
    },
    {
      id: "fetal-insurance",
      from: 6,
      to: 20,
      category: "finance",
      verification: "video",
      title: "태아보험은 검사 일정 전에 비교 시작",
      body: "기형아 검사 전후로 가입 조건과 고지 범위가 달라질 수 있어 약관, 면책, 특약, 보험료를 미리 비교합니다.",
      source: "영상: 태아보험 타이밍",
    },
    {
      id: "post-office-insurance",
      from: 6,
      to: 22,
      category: "finance",
      verification: "needs_check",
      title: "우체국 무료 공익보험 확인",
      body: "영상에서 '대한민국 엄마보험' 화면과 함께 22주 이내 가입을 강조합니다. 태아보험과 별도로 가입 가능 여부를 확인합니다.",
      source: "영상: 10주 전 준비",
      warning: "공식 검색 결과 없음: 우체국보험 사이트에서 엄마보험 문구를 확인하지 못함",
    },
    {
      id: "postpartum-center",
      from: 6,
      to: 16,
      category: "booking",
      verification: "video",
      title: "산후조리원 후보 투어와 예약",
      body: "영상에서는 5주차부터 문의했고 상담이 두 달 뒤인 곳도 있었다고 말합니다. 예약금 환불 기준, 투어 일정, 시설 조건을 확인합니다.",
      source: "영상: 조리원 예약 타이밍",
    },
    {
      id: "train-benefits",
      from: 8,
      to: 32,
      category: "official",
      verification: "official",
      title: "KTX·SRT 임산부 혜택 등록",
      body: "정부24 기준 KTX는 출산예정일+1년까지 특/우등실 요금 면제 또는 일반실 40% 할인, SRT는 지정 좌석 운임 30% 할인입니다.",
      source: "정부24 맘편한 코레일",
      href: sources.govKtx,
      warning: "SRT 세부 조건은 정부24 SRT 임산부 할인 페이지에서 별도 확인",
    },
    {
      id: "local-benefits",
      from: 8,
      to: 28,
      category: "official",
      local: true,
      verification: "general",
      title: "지역별 숨은 혜택 확인",
      body: "교통비, 택시, 축하금, 산전검사, 주차·공공시설 감면은 지자체별로 다릅니다. 거주지 보건소와 지자체 페이지에서 확인합니다.",
      source: "영상: 임산부 전용 숨은 혜택",
      warning: "지역별 확인 필요",
    },
    {
      id: "workplace-rights",
      from: 8,
      to: 12,
      category: "official",
      verification: "partial",
      introducedAt: verifiedDate,
      title: "직장인이라면 임산부 근로 보호 제도 확인",
      body: "영상에서는 회사가 거부하는 경우도 언급합니다. 태아검진 시간, 임신기 근로시간 단축, 야간·휴일근로 제한의 신청 방식과 증빙을 확인합니다.",
      source: "찾기쉬운 생활법령정보 일부 확인",
      href: sources.easyLawMaternity,
      warning: "회사 규정과 최신 노동부 안내 확인 필요",
    },
    {
      id: "car-insurance",
      from: 6,
      to: 28,
      category: "finance",
      verification: "general",
      introducedAt: verifiedDate,
      title: "자동차보험 임산부 할인 특약 확인",
      body: "현재 가입 보험사에 임신확인서와 가족관계증명서 기준으로 임산부 할인 특약 적용 또는 환급 가능 여부를 문의합니다.",
      source: "영상: 모르고 지나치는 돈 되는 혜택",
      warning: "보험사별 특약이라 공통 공식 기준 없음",
    },
    {
      id: "essential-apps",
      from: 6,
      to: 16,
      category: "personal",
      verification: "video",
      title: "초음파·주차별 정보 앱 세팅",
      body: "영상은 마미톡, 베이비빌리, 맘가이드를 예시로 들며 초음파 저장, 주수별 정보, 임산부 제품 성분 확인 용도로 소개합니다.",
      source: "영상: 10주 전 준비",
    },
    {
      id: "birth-hospital",
      from: 8,
      to: 16,
      category: "hospital",
      verification: "video",
      title: "출산 병원과 응급 이송 동선 확인",
      body: "고위험 가능성이 있으면 대학병원 분만실 예약을 서두르고, 일반 병원도 응급 상황 시 이송 가능한 병원인지 확인합니다.",
      source: "영상: 10주 전 준비",
    },
    {
      id: "outpatient-discount",
      from: 4,
      to: 40,
      category: "official",
      verification: "needs_check",
      introducedAt: verifiedDate,
      title: "임산부 외래 진료 본인부담금 감면 확인",
      body: "영상 화면에서 건강보험 적용 병원 외래 진료 시 임산부 의료비 본인부담금 20% 감면 혜택을 소개합니다.",
      source: "영상: 추가로 챙기면 좋은 혜택",
      warning: "공식 검색 결과 없음: NHIS/법령 검색에서 동일 문구를 확인하지 못함",
    },
    {
      id: "vaccines",
      from: 12,
      to: 36,
      category: "hospital",
      verification: "partial",
      title: "임신 중 예방접종 일정 확인",
      body: "질병관리청 기준 임신부는 임신 주수와 관계없이 인플루엔자 국가예방접종을 받을 수 있습니다. B형간염·백일해는 담당 의료진과 확인합니다.",
      source: "질병관리청 예방접종도우미 일부 확인",
      href: sources.kdcaFlu,
      warning: "백일해/B형간염 접종 가능 여부는 담당 의료진 기준 우선",
    },
    {
      id: "airport-benefits",
      from: 4,
      to: 40,
      category: "official",
      verification: "needs_check",
      introducedAt: verifiedDate,
      title: "공항 교통약자 혜택 확인",
      body: "영상은 인천공항 패스트트랙, 체크인 카운터 교통약자 스티커, 김포공항 포티케어 서비스를 예시로 듭니다.",
      source: "영상: 임산부만 가능한 숨은 혜택",
      warning: "공식 검색 결과 없음: airport.kr에서 임산부/패스트트랙/포티케어 문구를 확인하지 못함",
    },
    {
      id: "private-discounts",
      from: 4,
      to: 40,
      category: "personal",
      verification: "general",
      introducedAt: verifiedDate,
      title: "민간 임산부 할인 메모",
      body: "영상은 성심당 줄 서기 예외와 동반 1인, 일부 식당·뷔페 임산부 할인을 예시로 듭니다. 방문 전 매장별 조건을 확인합니다.",
      source: "영상: 임산부만 가능한 숨은 혜택",
      warning: "민간 혜택은 매장별 수시 변경",
    },
    {
      id: "anomaly-scan",
      from: 18,
      to: 22,
      category: "hospital",
      verification: "general",
      title: "정밀초음파와 중기 검사 일정 관리",
      body: "병원 예약일과 검사 전 안내사항을 캘린더에 등록합니다.",
      source: "일반 임신 진료 흐름",
    },
    {
      id: "birth-plan",
      from: 28,
      to: 34,
      category: "personal",
      verification: "general",
      title: "분만 병원과 출산 가방 준비",
      body: "입원 절차, 보호자 동선, 제왕절개 가능성, 산모·아기 준비물을 확인합니다.",
      source: "일반 임신 준비 흐름",
    },
    {
      id: "postpartum-helper",
      from: 33,
      to: 42,
      category: "official",
      verification: "official",
      title: "산모·신생아 건강관리 지원 신청",
      body: "정부24 기준 출산예정일 40일 전부터 출산일로부터 30일까지 신청 가능하며, 서비스기간과 정부지원금은 태아유형·출산순위·소득구간에 따라 달라집니다.",
      source: "정부24 산모·신생아 건강관리 지원",
      href: sources.govPostpartumHelper,
    },
    {
      id: "postpartum-helper-booking",
      from: 28,
      to: 34,
      category: "booking",
      verification: "video",
      title: "산후도우미 업체 후보 미리 비교",
      body: "복지로에서 예상 지원액을 확인하고, 사회서비스 전자바우처에서 제공기관 검색, 품질평가 등급, 가격, 만족도 조사 결과를 비교합니다.",
      source: "영상: 산후도우미 예약 타이밍",
    },
  ];

  return { sources, tasks, verificationLabels, verifiedDate };
})();
